# This is a basic workflow to help you get started with Actions

name: hello

on:
  repository_dispatch:
    types: [hello]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: echo Hello, world!
