# This is a basic workflow to help you get started with Actions

name: hello

on:
  repository_dispatch:
    types: [hello]
  # push:
  #   branches:
  #     - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: read message
      run: |
        echo "${{ toJSON(github.event.action) }}"
        echo "${{ toJSON(github.event.client_payload) }}"
